language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.9.3
script:
  - bundle exec rake db:reset RAILS_ENV=test
  - bundle exec rake test RAILS_ENV=test
